### ISSUE TITLE
Form contacto

### ISSUE THREAD

**Issue by Nidev-lab** [LuciusTCF/frontend-vetvida#49]
## Proceso

1. Ingrese a la pagina.
2. Quise hacer una consulta.

## Resultado esperado

• Que no se permitan colocar numero ni signos en el nombre del usuario o cliente.
• Que al enviar la consulta no se muestre ningun mensaje por consola.

## Resultado actual

• Se permiten colocar numeros y signos en el nombre.
• Al enviar la consulta se muestra un mensaje por consola.

## Captura

![image](https://github.com/LuciusTCF/frontend-vetvida/assets/53904695/a1636967-92b9-4a59-b4ca-d0a31ed5ce52)
![image](https://github.com/LuciusTCF/frontend-vetvida/assets/53904695/d7083304-e50f-4713-b103-d899e149f85f)
![image](https://github.com/LuciusTCF/frontend-vetvida/assets/53904695/a5fd1895-b25e-490f-a4ee-1ca1f9410057)

Cualquier cosita pueden contactarme a nicogonzalez2008@gmail.com o por el slack de RollingCode

**Comment by AlejandraAz** [comment]
Los cambios ya se realizaron, necesito su opinión, gracias.
