### ISSUE TITLE
Problemas de responsividad

### ISSUE THREAD

**Issue by Nidev-lab** [LuciusTCF/frontend-vetvida#50]
## Proceso

1. Ingrese a la pagina en mobile.
2. Quise registrarme.

## Resultado esperado

• Encontrar un formulario de registro en condiciones.

## Resultado actual

• Al ingresar el form de registro se encuentra fuera de forma.

## Captura

![image](https://github.com/LuciusTCF/frontend-vetvida/assets/53904695/a2e93ce2-7449-41d9-b7fb-708df7f9b169)

Cualquier cosita pueden contactarme a nicogonzalez2008@gmail.com o por el slack de RollingCode

**Comment by AlejandraAz** [comment]
Los cambios fueron realizados, necesito su opinión.
