### ISSUE TITLE
Form registro

### ISSUE THREAD

**Issue by Nidev-lab** [LuciusTCF/frontend-vetvida#52]
## Proceso

1. Ingrese a la pagina.
2. Me quise registrar con un usuario.

## Resultado esperado

• Que no se permita colocar numeros ni signos en el nombre del usuario o cliente.
• Que no se permitan colocar letras en el teléfono requerido.

## Resultado actual

• Se permite colocar numero y signo en el nombre.
• Se permiten colocar letras en el teléfono del usuario.

## Captura

![image](https://github.com/LuciusTCF/frontend-vetvida/assets/53904695/ff85d198-b3cf-40fb-90b6-9c10fc90f19d)
![image](https://github.com/LuciusTCF/frontend-vetvida/assets/53904695/49601d7e-7f27-4e51-b0f0-ccad48665764)

Cualquier cosita pueden contactarme a nicogonzalez2008@gmail.com o por el slack de RollingCode

**Comment by AlejandraAz** [comment]
Los errores ya fueron resueltos, necesito su opinión,gracias.
