### ISSUE TITLE
Error al registrar usuario

### ISSUE THREAD

**Issue by Nidev-lab** [LuciusTCF/frontend-vetvida#60]
## Proceso

1. Ingrese a la pagina.
2. Me quise registrar con un usuario.

## Resultado esperado

• Que la completar el formulario de registro poder crear mi usuario sin problemas.

## Resultado actual

• Al completar el registro con todos los datos solicitados se muestra un error por consola y no me puedo registrar. 

## Captura

![image](https://github.com/LuciusTCF/frontend-vetvida/assets/53904695/400d7652-8e7c-40fb-9c7c-ffe78d7c4932)

Cualquier cosita pueden contactarme a nicogonzalez2008@gmail.com o por el slack de RollingCode

**Comment by AlejandraAz** [comment]
Buen día! Te comento que estuve realizando las pruebas de registro de usuario con Lucas, que es otro participante, y ambos pudimos registrar un  nuevo usuario, no estamos teniendo inconvenientes respecto a eso.
